// ============================================================
// LANGUAGE: French i18n system
// ============================================================

const translations = {
    fr: {
        // App
        appName: 'Point de Vente',
        pageTitle: 'Point de Vente',
        scannerReady: 'Scanner actif',
        scannerIndicatorTitle: 'Scanner prêt - Double-clic pour réinitialiser',

        // Navigation
        navCheckout: '💳 Caisse',
        navInventory: '📦 Stock',
        navCustomers: '👤 Clients',
        navSuppliers: '🏷️ Fournisseurs',
        navAnalytics: '📊 Analytics',
        navSalesHistory: '🧾 Historique des ventes',
        navPromotions: '🏷️ Promotions',
        salesHistory: '🧾 Historique des Ventes',
        totalSales: 'Ventes totales',
        saleId: 'ID Vente',
        customer: 'Client',
        items: 'Articles',
        total: 'Total',
        paid: 'Payé',
        status: 'Statut',
        actions: 'Actions',
        view: 'Voir',
        delete: 'Supprimer',
        saleDetails: 'Détails de la Vente',
        date: 'Date',
        product: 'Produit',
        quantity: 'Quantité',
        price: 'Prix',
        allCustomers: 'Tous les clients',
        filter: 'Filtrer',
        reset: 'Réinitialiser',
        confirmDeleteSale: '⚠️ Supprimer cette vente ?',
        saleDeleted: '✅ Vente supprimée',
        errorDeletingSale: '❌ Échec de la suppression de la vente',
        errorFetchingSales: '❌ Échec de la récupération des ventes',
        errorFetchingCustomerSales: '❌ Échec de la récupération des ventes du client',
        errorFetchingDateRangeSales: '❌ Échec de la récupération des ventes pour cette période',
        errorShowingSaleDetails: '❌ Échec de l’affichage des détails de la vente',
        saleNotFound: '❌ Vente introuvable',
        noSalesFound: 'Aucune vente trouvée',
        saleRestored: '✅ Vente restaurée',
        errorRestoringSale: '❌ Échec de la restauration de la vente',

        // Promotions
        promoManagement: '🏷️ Gestion des Promotions',
        promoName: 'Nom de la promotion *',
        promoNamePlaceholder: 'ex: Soldes 2025',
        promoType: 'Type de promotion',
        promoPercentage: 'Pourcentage (%)',
        promoFixed: 'Montant fixe ({{currency}})',
        promoBuyXGetY: 'Achetez X, Obtenez Y Gratuit',
        promoTiered: 'Réduction par quantité (Achetez ≥ N)',
        promoCartPercentage: 'Réduction % sur total (min. achat)',
        promoCartFixed: 'Réduction fixe sur total (min. achat)',
        promoValue: 'Valeur (%)',
        promoBuyQty: 'Achetez (X) *',
        promoGetQty: 'Obtenez Gratuit (Y) *',
        promoMinQty: 'Quantité minimale (N) *',
        promoMinAmount: 'Montant minimum ({{currency}}) *',
        promoScope: 'Portée',
        promoAllProducts: 'Tous les produits',
        promoCategory: 'Catégorie spécifique',
        promoProduct: 'Produit spécifique (barcode)',
        promoSupplier: 'Fournisseur spécifique',
        promoClient: 'Client spécifique',
        promoPriceMin: 'Prix ≥ ({{currency}})',
        promoPriceMax: 'Prix ≤ ({{currency}})',
        promoScopeValue: 'Valeur de la portée',
        promoScopePlaceholder: 'Nom de catégorie ou barcode',
        promoHelpAll: 'Applique la promotion à tous les produits du catalogue, quel que soit leur prix ou leur origine.',
        promoHelpCategory: 'N\'applique la promotion qu\'aux produits appartenant à la catégorie sélectionnée.',
        promoHelpProduct: 'N\'applique la promotion qu\'au produit (code-barres) sélectionné.',
        promoHelpSupplier: 'N\'applique la promotion qu\'aux produits provenant du fournisseur sélectionné.',
        promoHelpClient: 'N\'applique la promotion qu\'au client sélectionné. La remise s\'active uniquement pour ce client lors de l\'encaissement.',
        promoHelpPriceMin: 'N\'applique la promotion qu\'aux produits dont le prix est supérieur ou égal au montant saisi.',
        promoHelpPriceMax: 'N\'applique la promotion qu\'aux produits dont le prix est inférieur ou égal au montant saisi.',
        promoValueHelpAll: 'Aucune valeur requise : la promotion s\'applique à tout le catalogue.',
        promoValueHelpCategory: 'Sélectionnez la catégorie concernée par la promotion.',
        promoValueHelpProduct: 'Sélectionnez le produit (code-barres) concerné par la promotion.',
        promoValueHelpSupplier: 'Sélectionnez le fournisseur dont les produits seront concernés par la promotion.',
        promoValueHelpClient: 'Sélectionnez le client qui bénéficiera de la promotion lors de l\'encaissement.',
        promoValueHelpPriceMin: 'Saisissez le prix minimum (seuil) en {{currency}} : les produits à ce prix ou au-dessus sont concernés.',
        promoValueHelpPriceMax: 'Saisissez le prix maximum (plafond) en {{currency}} : les produits à ce prix ou en dessous sont concernés.',
        promoStartDate: 'Date début',
        promoEndDate: 'Date fin',
        promoNoPromotions: 'Aucune promotion créée',
        promoActive: 'Actif',
        promoInactive: 'Inactif',
        promoSave: '💾 Enregistrer',
        promoUpdate: '💾 Mettre à jour',
        promoClear: 'Effacer',
        promoList: '📋 Liste des Promotions',
        promoNameRequired: '⚠️ Nom requis',
        promoInvalidPercent: '⚠️ Pourcentage invalide (1-100)',
        promoInvalidAmount: '⚠️ Montant invalide',
        promoInvalidQtyXY: '⚠️ Quantités X/Y invalides',
        promoInvalidMinQty: '⚠️ Quantité minimale invalide',
        promoInvalidMinAmount: '⚠️ Montant minimum invalide',
        promoScopeValueRequired: '⚠️ Valeur de portée requise',
        promoCreated: '✅ Promotion créée',
        promoUpdated: '✅ Promotion mise à jour',
        promoDeleted: '✅ Promotion supprimée',
        promoDeleteConfirm: '⚠️ Supprimer cette promotion ?',

        navSettings: '⚙️ Paramètres',
        navUsers: '🗣️ Utilisateurs',

        // User switch
        userSwitchTitle: 'Changer d\'utilisateur',
        btnSwitchUser: 'Déconnexion',

        // Backup
        backupAutoEnabled: '💾 Sauvegarde automatique activée - Cliquez pour désactiver',
        backupAutoDisabled: '💾 Sauvegarde automatique désactivée - Cliquez pour activer',

        // Checkout
        customer: 'Client:',
        regularCustomer: 'Client régulier (sans profil)',
        newCustomer: '➕ Nouveau',
        product: 'Produit',
        barcode: 'Code-barres',
        unit: 'Unité',
        price: 'Prix (DA)',
        reducedPrice: 'Prix réduit',
        qty: 'Qté',
        subtotal: 'Sous-total (DA)',
        emptyCart: 'Aucun article dans le panier — Scannez un code-barres pour commencer',
        quickCartEmpty: 'Aucun article rapide pour le moment',
        transactionSummary: '🧾 Résumé de la Transaction',
        paymentSection: '💵 Paiement',
        subtotalLabel: 'Sous-total',
        vat: 'TVA',
        discount: 'Remise',
        total: 'Total',
        amountPaid: 'Montant payé (DA):',
        remaining: 'Reste à payer:',
        paid: '✅ Payé',
        notPaid: '❌ Non Payé',
        itemsInCart: 'articles dans le panier',
        completeSale: '✅ Finaliser la vente',
        clear: '🗑 Vider',
        piece: 'pièce',

        // Product form
        addProduct: '➕ Ajouter / Modifier un Produit',
        save: '💾 Enregistrer',
        clearForm: 'Effacer',
        deleteAllProducts: '⚠️ Supprimer tous les produits',
        editProduct: '✏️ Modifier le produit',
        update: '💾 Mettre à jour',
        cancel: 'Annuler',

        // Customer management
        customerManagement: '👤 Gestion des Clients',
        fullName: 'Nom complet *',
        phone: 'Téléphone',
        address: 'Adresse',
        saveCustomer: '💾 Enregistrer le client',
        deleteAllCustomers: '⚠️ Supprimer tous les clients',
        searchCustomer: '🔍 Rechercher un client...',
        noCustomers: 'Aucun client trouvé',
        noProducts: 'Aucun produit dans le catalogue',
        totalDebt: '💰 Dettes totales des clients',
        customersWithDebt: '👥 Clients avec dettes',

        // Analytics
        revenue: '💰 Chiffre d\'affaires',
        transactions: '🧾 Transactions',
        itemsSold: '📦 Articles vendus',
        averageOrder: '📊 Panier moyen',
        exportCSV: '📥 Exporter CSV',
        exportJSON: '📄 Exporter JSON',
        clearSales: '🗑 Effacer les ventes',

        // Settings
        settingsTitle: '⚙️ Paramètres',
        settingsSubtitle: 'Configuration du système',
        vatRate: 'Taux de TVA (%)',
        lowStockThreshold: 'Seuil de stock bas',
        currencySymbol: 'Symbole de la devise',
        saveSettings: '💾 Sauvegarder',
        resetSettings: '↺ Réinitialiser',
        resetAll: '⚠️ Tout réinitialiser',
        fullBackup: '💾 Sauvegarde complète',
        restoreBackup: 'Restaurer une sauvegarde',
        systemInfo: '📊 Informations système',
        database: 'Base de données',
        storage: 'Stockage',
        noSales: 'Aucune vente enregistrée',

        // Partial payment / debts
        partialPayment: '💰 Paiement Partiel',
        amountToPay: 'Montant à payer (DA):',
        remainingAfterPayment: 'Dette restante après paiement:',
        applyPartialPayment: '💰 Appliquer le paiement partiel',
        debtHistory: '📋 Historique des dettes',
        paySelected: '💰 Payer les dettes sélectionnées',
        close: 'Fermer',
        noDebt: 'Aucune dette - Tout est payé !',
        pending: '⏳ En attente',
        paidStatus: '✅ Payé',
        partialStatus: '⏳ Partiel',
        debtStatus: '⚠️ Dette',

        // Stats
        products: 'produits',
        lowStock: 'stock bas',
        totalValue: 'valeur totale',

        // Toast messages
        scanBarcode: '📦 Code-barres chargé',
        barcodeNotFound: '❌ Produit avec le code "{{barcode}}" introuvable',
        outOfStock: '❌ {{name}} est en rupture de stock !',
        addedToCart: '✅ {{name}} ajouté au panier',
        transactionComplete: '✅ Transaction complète ! Total: {{total}}',
        debtCreated: '✅ Vente enregistrée - Dette: {{total}}',
        cartCleared: 'Panier vidé',
        settingsSaved: '✅ Paramètres sauvegardés !',
        settingsError: '❌ Échec de la sauvegarde',
        optimizeDbDone: '✅ Base de données optimisée',
        records: 'enregistrements',
        cacheCleared: '✅ Cache vidé',
        logsExported: '✅ Logs exportés',
        customerSaved: '✅ Client "{{name}}" enregistré !',
        customerDeleted: '✅ Client supprimé',
        productSaved: '✅ Produit "{{name}}" ajouté !',
        productUpdated: '✅ Produit "{{name}}" mis à jour !',
        productDeleted: '✅ Produit supprimé',
        allProductsDeleted: '✅ Tous les produits supprimés',
        allCustomersDeleted: '✅ Tous les clients supprimés',
        allSalesDeleted: '✅ Toutes les ventes supprimées',
        csvExported: '✅ CSV exporté avec succès !',
        jsonExported: '✅ Sauvegarde JSON exportée !',
        dataImported: '✅ Données importées avec succès !',
        dataReset: '✅ Toutes les données ont été réinitialisées',
        backupRestored: '🔄 Sauvegarde automatique restaurée',
        scannerReset: '🔄 Scanner réinitialisé',
        scanError: '❌ Erreur lors du scan',
        enterBarcodeOrName: '⚠️ Entrez un code-barres ou un nom',
        scannerInactive: '⚠️ Scanner inactif dans cette vue',
        invalidBarcode: '⚠️ Code-barres invalide',
        invalidBarcodeLong: '⚠️ Code-barres invalide (trop long)',
        scannerStuck: '⚠️ Scanner bloqué - relâchez le bouton',
        cartEmpty: '❌ Panier vide !',
        productNotFound: '❌ Produit "{{name}}" introuvable',
        insufficientStock: '❌ Stock insuffisant pour "{{name}}" (disponible: {{stock}})',
        stockWarning: '⚠️ Stock faible pour "{{name}}" (disponible: {{stock}})',
        transactionFailed: '❌ Échec de la transaction: {{error}}',
        selectDebt: '⚠️ Veuillez sélectionner au moins une dette',
        debtPaid: '✅ {{count}} dette(s) marquée(s) comme payée(s) !',
        allDebtsPaid: '✅ Toutes les dettes marquées comme payées',
        partialPaymentApplied: '✅ Paiement partiel de {{amount}} appliqué !\nDette restante: {{remaining}}',
        partialPaymentError: '❌ Échec du paiement partiel',
        invalidAmount: '⚠️ Veuillez entrer un montant valide',
        amountExceedsDebt: '⚠️ Le montant dépasse la dette totale ({{total}})',
        customerHasDebt: '💡 Ce client a une dette de {{total}}',
        newTransaction: '🔄 Nouvelle transaction prête - Appuyez sur Espace pour recommencer',
        deleteFailed: '❌ Échec de la suppression',
        resetFailed: '❌ Échec de la réinitialisation',
        noBackupData: 'ℹ️ Aucune sauvegarde trouvée. Commencez par ajouter des produits.',
        appReady: '🧵 ShopPOS Pro prêt - Scannez un code-barres pour commencer !',
        initFailed: '❌ Échec de l\'initialisation: ',
        folderNotSupported: '⚠️ Votre navigateur ne supporte pas la sélection de dossier.',
        folderError: '❌ Impossible de sélectionner le dossier',
        loadFailed: '❌ Échec du chargement',
        refreshData: '🔄 Rafraîchissement des données...',
        dataUpdated: '✅ Données mises à jour',
        dayClosed: '🔒 Journée clôturée — suppression interdite',
        saleNotFound: '❌ Vente non trouvée',
        detailLoadError: '❌ Erreur lors du chargement des détails',
        dayClosedEdit: '🔒 Journée clôturée — modification interdite',
        noSaleSelected: '❌ Aucune vente sélectionnée',
        moveError: '❌ Erreur lors du dépointage',
        zReportModuleMissing: '⚠️ Module Rapport Z non chargé',
        quantityZero: '⚠️ La quantité doit être supérieure à 0',
        cancelled: 'Annulé',
        invalidQuantity: '⚠️ Veuillez entrer une quantité valide (ex: 2.5)',
        quickClientOff: '⚡ Mode client rapide désactivé',
        quickClientOn: '⚡ Mode client rapide activé',
        quickClientNothing: '⚡ Aucun article rapide à finaliser',
        quickClientDone: '⚡ Vente client rapide finalisée',
        cartRestored: '♻️ Panier restauré',
        accessDenied: '⚠️ Accès refusé — rôle insuffisant',
        categoryPrompt: 'Entrez le nom de la nouvelle catégorie:',
        categoryError: '❌ Erreur lors de la création de la catégorie',
        categoryDeleteError: '⚠️ Impossible de supprimer cette catégorie',
        unsupportedFormat: '⚠️ Format non supporté. Utilisez JPG, PNG, GIF ou WebP',
        invalidCategoryName: '⚠️ Nom de catégorie invalide',
        productRemoved: '🗑️ Produit supprimé',
        allProductsRemoved: '🗑️ Tous les produits ont été supprimés',
        productLoadError: '❌ Produit non trouvé',
        updateError: '❌ Erreur lors de la mise à jour',
        cartEmptyAddFirst: 'ℹ️ Panier vide - Ajoutez des articles d\'abord',
        cartAlreadyEmpty: 'ℹ️ Panier déjà vide',
        usePageUpInCheckout: 'ℹ️ Utilisez la touche Page Up dans la vue Caisse',
        usePageDownInCheckout: 'ℹ️ Utilisez la touche Page Down dans la vue Caisse',
        printing: '🖨️ Impression en cours...',
        printFunctionUnavailable: '❌ Fonction d impression non disponible',
        enterBarcodeManually: '📝 Entrez le code-barres manuellement',
        editReducedPriceFor: '📝 Modifier le prix réduit pour: {{name}}',
        reducedPriceFor: '📝 Prix réduit pour: {{name}}',
        itemRemoved: '🗑️ Retiré: {{qty}}{{unit}} {{name}}',
        quickClientLabel: '⚡ Client rapide',
        quickClientOnLabel: '⚡ Client rapide ON',
        noArticlesPrint: '❌ Aucun article à imprimer',
        printSent: '🖨️ Impression envoyée !',
        printError: '❌ Erreur d\'impression',
        error: '❌ Erreur',
        supplierUpdated: '✅ Fournisseur mis à jour',
        supplierAdded: '✅ Fournisseur ajouté',
        supplierDeleted: '✅ Fournisseur supprimé',
        supplierNameRequired: '⚠️ Le nom du fournisseur est requis',
        supplierNotFound: '❌ Fournisseur introuvable',
        selectSupplier: '⚠️ Veuillez sélectionner un fournisseur',
        selectDate: '⚠️ Veuillez sélectionner une date',
        receptionSaved: '✅ Réception enregistrée — ',
        itemsAddedToStock: 'article(s) ajoutés au stock',
        addAtLeastOneItem: '⚠️ Ajoutez au moins un article',
        receptionDeleted: '✅ Réception supprimée',
        receiptConfirm: '📦 Enregistrer la réception de ',
        receiptDeleteConfirm: '⚠️ Supprimer cet enregistrement de réception ?\n\nLe stock ne sera pas décrémenté automatiquement.',
        zReportNoSales: '⚠️ Aucune vente enregistrée aujourd\'hui.\n\nVoulez-vous quand même générer un rapport Z vide ?',
        zReportClosingConfirm: '🔒 Clôture de caisse — {{count}} vente(s) aujourd\'hui\n\nCela va :\n  1. Générer le Rapport Z\n  2. Verrouiller les ventes du jour (pas de suppression/modification)\n  3. Imprimer le rapport\n\nContinuer ?',
        noReportToPrint: '❌ Aucun rapport à imprimer',
        zReportPrintError: '❌ Aucun rapport à imprimer',
        zReportPrintSent: '🖨️ Rapport Z envoyé à l\'imprimante',
        zReportAlreadyClosed: '⚠️ La journée d\'aujourd\'hui est déjà clôturée',
        zReportGenerating: '⏳ Génération du rapport Z...',
        zReportDone: '✅ Rapport Z généré et journée verrouillée !',
        zReportError: '❌ Erreur lors de la clôture: ',
        saleCreditNeedsClient: '⚠️ La vente à crédit nécessite un client sélectionné',
        userCreated: '✅ Utilisateur créé',
        userEdited: '✅ Utilisateur modifié',
        pinChanged: '✅ PIN modifié',
        cannotDeactivateSelf: '⚠️ Vous ne pouvez pas vous désactiver vous-même',
        userDeleted: '✅ Utilisateur supprimé',
        nameUpdated: '✅ Nom mis à jour',
        autoBackupOn: '💾 Sauvegarde automatique ACTIVÉE',
        autoBackupOff: '⏸️ Sauvegarde automatique DÉSACTIVÉE',
        cloudBackupOn: '☁️ Sauvegarde cloud ACTIVÉE',
        cloudBackupOff: '☁️ Sauvegarde cloud DÉSACTIVÉE',
        cloudBackupFolderNeeded: 'ℹ️ Sélectionnez un dossier pour la sauvegarde cloud',
        updateApplied: '🔄 Nouvelle version détectée — rechargement...',
        updateReady: '🔄 Nouvelle version disponible — recharger pour appliquer',
        noDataBackup: 'ℹ️ Aucune donnée à sauvegarder',
        backupInProgress: '💾 Sauvegarde en cours...',
        backupDone: '✅ Sauvegarde terminée !',
        backupError: '❌ Erreur lors de la sauvegarde',
        analyticsLoadError: '❌ Échec du chargement des analytics',
        accessDeniedRole: '⚠️ Accès refusé — rôle insuffisant',
        importError: '❌ Échec de l\'importation',
        invalidBackupFormat: '❌ Format de sauvegarde invalide',
        csvExportError: '❌ Échec de l\'export CSV',
        jsonExportError: '❌ Échec de l\'export JSON',
        clientLoadError: '❌ Échec du chargement des clients',
        saveFailed: '❌ Échec de l\'enregistrement',
        clientNotFound: '❌ Client non trouvé',
        paymentFailed: '❌ Échec du paiement',
        noUnpaidDebt: '✅ Aucune dette impayée',
        noClientSelected: '❌ Aucun client sélectionné',
        importReplaceConfirm: '⚠️ Cela va remplacer toutes les données actuelles. Continuer ?',
        deleteAllSalesConfirm: '⚠️ Supprimer TOUTES les ventes ? Cette action est irréversible !',
        resetAllConfirm: '⚠️⚠️⚠️ RÉINITIALISER TOUTES LES DONNÉES ? Cette action est irréversible !',
        resetAreYouSure: 'Êtes-vous absolument sûr ?',
        resetTypeToConfirm: 'Tapez exactement RÉINITIALISER pour confirmer l\'effacement complet de toutes les données :',
        resetCancelled: 'Réinitialisation annulée.',
        importRolledBack: 'Échec de l\'import. Les données d\'origine ont été restaurées.',
        storageSwitchDone: 'Emplacement des données modifié.',
        storageSwitchCancelled: 'Changement d\'emplacement annulé.',
        deleteAllSalesStock: '⚠️⚠️⚠️ Supprimer TOUTES les ventes ?\n\nTous les articles seront RESTITUÉS au stock.',
        deleteAllSalesStockConfirm: '⚠️⚠️⚠️ Supprimer TOUTES les ventes ?\n\nTous les articles seront RESTITUÉS au stock.\n\n⚠️ Cette action est irréversible !',
        deleteAllCustomersConfirm: '⚠️ Supprimer TOUS les clients ? Cette action est irréversible !',
        deleteAllProductsConfirm: '⚠️ Supprimer TOUS les produits ? Cette action est irréversible !',
        markAllDebtsPaid: 'Marquer TOUTES les dettes ({{total}} {{currency}}) comme payées ?',
        categoryExists: '⚠️ Cette catégorie existe déjà',
        uncategorized: 'Non catégorisé',
        newCategoryPlaceholder: '➕ Nouvelle catégorie...',
        selectCategory: '-- Sélectionner une catégorie --',
        noProductsFound: 'Aucun produit ne correspond à la recherche',
        noCategoryCreated: 'Aucune catégorie créée',
        regularCustomerShort: 'Client régulier',
        previewAlt: 'Aperçu',
        noSalesRecorded: 'Aucune vente enregistrée',
        noRecentSales: 'Aucune vente récente',
        noRecentSales48h: 'Aucune vente dans les dernières 48 heures',
        noProductFound: 'Aucun produit trouvé',
        regularCustomerProfile: '🔄 Client régulier (sans profil)',
        regularCustomerSansProfil: '🔄 Client régulier (sans profil)',
        purchaseDetails: '🛒 Détails de l\'achat - ',
        zeroClose: '0 clôture(s)',
        noZReports: '🔒 Aucun rapport Z enregistré',
        closeDayTitle: '🔒 Clôture de caisse (Rapport Z)',
        noAuditEntries: 'Aucune entrée',
        userNotConfigured: 'Aucun utilisateur configuré',
        noSupplierRegistered: 'Aucun fournisseur enregistré',
        noReceptionRecorded: 'Aucune réception enregistrée',
        noReceptionForFilters: 'Aucune réception pour ces filtres',
        themeApplied: 'Thème appliqué',
        settingsDefaultLoaded: '↺ Paramètres par défaut chargés. Cliquez sur Sauvegarder pour appliquer.',
        invalidVatRate: '⚠️ Taux de TVA invalide',
        invalidLowStock: '⚠️ Seuil de stock invalide',
        currencyRequired: '⚠️ Symbole de devise requis',
        arabicNumerals: 'Chiffres arabes-indic',
        printFunctionUnavailable: '❌ Fonction d\'impression non disponible',
        cartEmptyAddFirst: '❌ Panier vide - Ajoutez des articles d\'abord',
        folderSelected: '✅ Dossier sélectionné.',
        backupSaved: '✅ Sauvegarde enregistrée: {{filename}}',
        backupDownloaded: '✅ Sauvegarde téléchargée: {{filename}}',
        saveFailedExcl: '❌ Échec de la sauvegarde',
        allDebtsPaidShort: '✅ Toutes les dettes sont payées',

        // Login / Lock screen
        lockTitle: 'Sélectionnez votre profil',
        forgotPassword: '🔑 Mot de passe oublié ?',
        back: '← Retour',
        pinTooShort: 'PIN trop court (4-6 chiffres)',
        pinIncorrect: 'PIN incorrect ({{attempt}}/{{max}})',
        pinLockout: '🔒 Trop de tentatives. Attendez {{seconds}} secondes...',
        pinTryAgain: 'Essayez à nouveau',
        userNotFoundDisabled: 'Utilisateur introuvable ou désactivé',
        adminPinRequired: '🔐 Confirmation Admin requise',
        adminPinSubtitle: 'Entrez le PIN d\'un administrateur',
        adminPinIncorrect: 'PIN Admin incorrect',
        forgotPinTitle: '🔑 Réinitialisation du PIN',
        forgotPinDesc: 'Créez un nouveau PIN pour votre compte.',
        changePinTitle: '🔑 Changement de PIN obligatoire',
        changePinDesc: 'Votre PIN par défaut (0000) doit être changé pour des raisons de sécurité.',
        newPinLabel: 'Nouveau PIN (4-6 chiffres) *',
        confirmPinLabel: 'Confirmer le PIN *',
        changePinBtn: '💾 Changer le PIN',
        pinChangedSuccess: '✅ PIN changé avec succès',
        pinChangeError: 'Erreur lors du changement de PIN',
        pinSaved: '✅ PIN enregistré',
        pinMinError: 'Le PIN doit contenir 4 à 6 chiffres',
        pinNoZero: 'Le PIN ne peut pas être 0000',
        pinMismatch: 'Les PINs ne correspondent pas',
        sessionLocked: '🔒 Session verrouillée pour inactivité',
        pleaseSelectProfile: '⚠️ Veuillez d\'abord sélectionner un profil',
        userNotFound: '⚠️ Utilisateur introuvable',
        selectProfileFirst: '⚠️ Sélectionnez d\'abord un profil',

        // Users management
        usersTitle: '🗣️ Gestion des Utilisateurs',
        createUser: '➕ Nouvel utilisateur',
        editUser: '✏️ Modifier l\'utilisateur',
        nameLabel: 'Nom *',
        pinLabel: 'PIN (4-6 chiffres) *',
        roleLabel: 'Rôle *',
        adminRole: 'Administrateur',
        caissierRole: 'Caissier',
        gerantRole: 'Gérant',
        nameRequired: 'Nom requis',
        pinRequired: 'PIN requis (4-6 chiffres)',
        pinMinMax: 'Le PIN doit contenir 4 à 6 chiffres',
        forcePinChange: '🔑 Forcer le changement de PIN à la prochaine connexion',
        permissionsTitle: '🔐 Permissions personnalisées',
        permissionsOptional: '(optionnel)',
        permissionsHint: 'Laissez vide pour utiliser les permissions par défaut du rôle.',
        saveUser: '💾 Enregistrer',
        noUsers: 'Aucun utilisateur',
        userHistory: 'Historique',
        userEdit: 'Modifier',
        userChangePin: 'Changer le PIN',
        userDeactivate: 'Désactiver',
        userActivate: 'Activer',
        userDelete: 'Supprimer',
        userDefaultPin: '⚠️ PIN par défaut',
        userDeactivated: '(désactivé)',
        userSelf: '(vous)',
        pinChangeFor: '🔑 Changer le PIN de ',
        changePinSave: '💾 Changer le PIN',
        pinModified: '✅ PIN modifié',
        pinChangeFailed: 'Erreur lors du changement',
        noPermission: '⚠️ Accès refusé — rôle insuffisant',
        admin: 'Admin',

        // Permission labels
        permSaleCreate: 'Créer des ventes',
        permSaleView: 'Voir les ventes',
        permSaleEdit: 'Modifier les ventes',
        permSaleDelete: 'Supprimer des ventes',
        permInventoryView: 'Voir le stock',
        permInventoryCreate: 'Ajouter des produits',
        permInventoryEdit: 'Modifier des produits',
        permInventoryDelete: 'Supprimer des produits',
        permCustomersView: 'Voir les clients',
        permCustomersCreate: 'Créer des clients',
        permCustomersDelete: 'Supprimer des clients',
        permAnalyticsView: 'Voir les analyses',
        permSuppliersView: 'Voir les fournisseurs',
        permSuppliersCreate: 'Créer des fournisseurs',
        permSettingsView: 'Voir les paramètres',
        permSettingsEdit: 'Modifier les paramètres',
        permUsersView: 'Voir les utilisateurs',
        permUsersManage: 'Gérer les utilisateurs',
        permZReportGenerate: 'Générer des Z-Rapports',
        permDataClear: 'Effacer les données',

        // Self profile
        selfProfile: 'Mon Profil',
        changeMyPin: '🔑 Changer mon PIN',

        // Language
        language: '🌐 Langue',
        langFr: 'FR',
        langAr: 'AR',

        // Currency
        currencyDA: 'DA',
        currencyDZD: 'دج',

        // Print receipt
        receiptTitle: '✦ TICKET DE CAISSE ✦',
        receiptThanks: 'MERCI !',

        // Z-Report
        zReportTitle: 'RAPPORT Z',
        zReportClosing: 'Clôture de caisse',
        zReportThanks: 'Merci pour votre travail !',

        // Audit actions
        auditSaleCreated: 'Vente créée',
        auditSaleDeleted: 'Vente supprimée',
        auditSaleEdited: 'Vente modifiée',
        auditSaleMoved: 'Vente déplacée',
        auditAllSalesDeleted: 'Toutes les ventes supprimées',
        auditPaymentReceived: 'Paiement reçu',
        auditProductCreated: 'Produit créé',
        auditProductEdited: 'Produit modifié',
        auditProductDeleted: 'Produit supprimé',
        auditAllProductsDeleted: 'Tous les produits supprimés',
        auditCustomerCreated: 'Client créé',
        auditCustomerDeleted: 'Client supprimé',
        auditAllCustomersDeleted: 'Tous les clients supprimés',
        auditZReport: 'Z-Rapport généré',
        auditUserCreated: 'Utilisateur créé',
        auditUserEdited: 'Utilisateur modifié',
        auditUserDeleted: 'Utilisateur supprimé',
        auditPinChanged: 'PIN modifié',
        auditLoginSuccess: 'Connexion réussie',
        auditLoginFailed: 'Tentative de connexion échouée',
        auditDataCleared: 'Données effacées',

        // Payment methods
        payCash: '💵 Espèces',
        payCheck: '📝 Chèque',
        payCCP: '🏦 CCP',
        payBaridiMob: '📱 BaridiMob',
        payCredit: '🔴 Crédit (dette)',
        payCashShort: 'Espèces',

        // Transaction status
        statusPaid: 'Payé',
        statusPartial: 'Partiel',
        statusCredit: 'Crédit',

        // Analytics
        salesByDay: 'Ventes par jour',
        topProducts: 'Produits les plus vendus',
        hourlyDistribution: 'Distribution horaire',
        paymentMethods: 'Modes de paiement',
        exportCsvProgress: '📥 Export CSV en cours...',
        exportJsonProgress: '📄 Export JSON en cours...',
        viewCustomerPurchase: '👁️ Aperçu de l\'achat',
        zReportHistory: 'Historique des Rapports Z',
        dailyBreakdownTitle: '📅 Détail par jour',
        dailyRevenue: 'Recette',
        dailyProfit: 'Bénéfice',
        dailyMargin: 'Marge',
        dailyItems: 'Articles',
        dailySales: 'Ventes',
        dailyTotal: 'TOTAL',
        daySummary: 'Résumé de la journée',
        salesHistoryTitle: 'Historique des ventes',
        lastCustomers: 'Clients récents (48h)',
        metricsCards: 'Indicateurs clés',
        inventoryMetrics: 'Inventaire',
        topSellingProducts: 'Les plus vendus',
        noProductsInCatalog: 'Aucun produit dans le catalogue',
        analyticsDashboardTitle: '📊 Tableau de Bord Analytique',
        todayLabel: 'Aujourd\'hui',
        thisWeekLabel: 'Cette semaine',
        thisMonthLabel: 'Ce mois',
        allTimeLabel: 'Tout temps',
        revenueLabel: 'Recette (DA)',
        profitLabel: 'Profit',
        salesLabel: 'Ventes',
        itemsLabel: 'Articles',
        avgOrderLabel: 'Panier moyen',
        totalMarginLabel: 'Marge totale',
        clientDebtsLabel: 'Dettes clients',
        customersInDebtLabel: 'Clients endettés',
        lowStockLabel: 'Stock bas',
        transactionsLabel: 'Transactions',
        stockValueSale: 'Valeur stock au prix de vente',
        stockValuePurchase: 'Valeur stock au prix d\'achat',
        potentialProfit: 'Bénéfice potentiel si tout vendu',
        totalStockLabel: 'Stock total',
        salesHistoryFull: '📜 Historique complet des ventes',
        allTransactionsDebts: 'Toutes les transactions incluant les dettes',
        zReportHistoryTitle: '🔒 Historique des Rapports Z (Clôtures)',
        dailyDataLoading: 'Chargement des données journalières...',
        noDailyData: 'Aucune donnée journalière disponible',
        historyLoading: 'Chargement de l\'historique...',
        noSalesInHistory: 'Aucune vente enregistrée dans l\'historique',
        zReportLoading: 'Chargement des rapports Z...',
        historyLoadError: '❌ Erreur de chargement de l\'historique',
        loadError: '❌ Erreur de chargement',
        deleteAllBtn: '🗑 Supprimer toutes',
        lastUpdate: 'Dernière mise à jour:',
        historyTotal: '📊 TOTAL HISTORIQUE:',
        transactionsWord: 'transaction(s)',
        profitWord: 'profit',
        deleteSaleConfirmMsg: '⚠️ Supprimer la vente #{{id}} ?\n\nLes articles seront RESTITUÉS au stock.',
        saleDeletedSuccess: '✅ Vente #{{id}} supprimée',
        itemsRestoredStock: ' article(s) restitués en stock',
        noStockRestored: '⚠️ Aucun stock restitué (produits introuvables)',
        deleteErrorMsg: '❌ Erreur lors de la suppression: {{error}}',
        deleteAllSalesStockMsg: '⚠️⚠️⚠️ Supprimer TOUTES les ventes ?\n\nTous les articles seront RESTITUÉS au stock.',
        confirmAreYouSure: 'Êtes-vous absolument sûr ?',
        allSalesDeletedMsg: '✅ Toutes les ventes supprimées - {{count}} article(s) restitués en stock',
        deleteAllError: '❌ Erreur lors de la suppression',
        saleLoadedCart: '♻️ Vente #{{id}} chargée dans le panier',
        cannotRestoreSale: '❌ Impossible de restaurer cette vente',
        cartContainsItems: '⚠️ Le panier contient {{count}} articles.\n\nRemplacer par la vente #{{id}} ?',
        purchaseDetailsTitle: '🛒 Détails de l\'achat - ',
        clientLabel: '👤 Client:',
        dateLabel: '📅 Date:',
        totalLabelDetail: '💰 Total:',
        statusLabel: '💳 Statut:',
        profitLabelDetail: '📈 Profit:',
        purchasedItemsLabel: '📦 Articles achetés:',
        remainingToPay: '⚠️ Reste à payer',
        editSaleTitle: '✏️ Modifier la vente #',
        editSaleCustomer: 'Client',
        editSalePaymentStatus: 'Statut de paiement',
        editSaleAmountPaid: 'Montant payé (DA)',
        editSaleTotalLabel: 'Total (DA)',
        editSaleArticles: '📦 Articles',
        editSaleSave: '💾 Sauvegarder',
        editSaleDelete: '🗑 Supprimer',
        editSaleCancel: 'Annuler',
        editSaleAddItem: '➕ Ajouter un article',
        editSaleNoValid: '⚠️ Aucun article valide',
        saleUpdatedMsg: '✅ Vente #{{id}} mise à jour',
        stockRestoredInfo: ' — {{count}} article(s) restitués au stock',
        stockDeductedInfo: ' — {{count}} article(s) déduits du stock',
        saveEditErrorMsg: '❌ Erreur lors de la sauvegarde',
        moveSaleTitle: '📅 Déplacer la vente',
        moveSaleDesc: 'Choisissez la nouvelle date pour cette vente.',
        moveSaleDateLabel: 'Nouvelle date',
        moveSaleConfirm: '📅 Déplacer',
        moveDateRequired: '⚠️ Veuillez choisir une date',
        saleMovedMsg: '✅ Vente #{{id}} déplacée du {{old}} au {{new}}',
        moveErrorMsg: '❌ Erreur lors du déplacement',
        chargeBtn: '↩ Charger',
        deplacerBtn: '📅 Déplacer',
        modifierBtn: '✏️ Modifier',
        supprimerBtn: '🗑 Supprimer',
        fermerBtn: 'Fermer',
        restoreToCartBtn: '↩ Charger dans le panier',
        editItemsBtn: '📝 Modifier les articles',
        tableHeaderID: 'ID',
        tableHeaderDate: 'Date',
        tableHeaderClient: 'Client',
        tableHeaderArticles: 'Articles',
        tableHeaderRecu: 'Reçu (DA)',
        tableHeaderPaye: 'Payé (DA)',
        tableHeaderReste: 'Reste (DA)',
        tableHeaderProfit: 'Profit',
        tableHeaderMarge: 'Marge',
        tableHeaderStatut: 'Statut',
        nonPaye: 'Non payé',
        partielShort: 'Partiel',
        payeeLabel: 'Payée',
        dateInconnue: 'Date inconnue',
        verrouille: 'Verrouillé',
        genereLe: 'Généré:',
        printZReportBtn: '🖨 Imprimer',
        timeAgoNow: "à l'instant",
        timeAgoMinutes: 'il y a {{n}} min',
        timeAgoHours: 'il y a {{n}}h',
        timeAgoDays: 'il y a {{n}}j',
        productsUnits: '{{count}} produits • {{units}} unités',
        sousTotal: 'Sous-total',
        searchProduct: '🔍 Rechercher un produit...',
        searchPlaceholder: '🔍 Rechercher...',
        horsStock: 'Hors stock',
        stockLabel: 'Stock:',
        recentLabel: 'Récent',
        noArticles: 'Aucun article',
        salesCountWord: 'vente(s)',
        articlesCountWord: 'article(s)',
        noSaleSelected: '❌ Aucune vente sélectionnée',
        saleNotFound: '❌ Vente introuvable',
        dayClosedSuppression: '🔒 Journée clôturée — suppression interdite',
        dayClosedModification: '🔒 Journée clôturée — modification interdite',
        saleDeletedAudit: 'Vente #{{id}} supprimée - {{count}} article(s) restitué(s)',
        saleEditedAudit: 'Vente #{{id}} modifiée - Total: {{total}}',
        saleMovedAudit: 'Vente #{{id}} déplacée du {{old}} au {{new}}',
        allSalesBulkDeleted: '{{count}} ventes supprimées - {{restored}} article(s) restitué(s)',

        // Day names
        dayDim: 'Dim',
        dayLun: 'Lun',
        dayMar: 'Mar',
        dayMer: 'Mer',
        dayJeu: 'Jeu',
        dayVen: 'Ven',
        daySam: 'Sam',

        // CSV headers
        csvHeader: 'ID Vente,Date,Client,Articles,Sous-total,TVA,Remise,Total,Payé,Reste,Statut',

        // Placeholder
        placeholderQty: 'Qté',
        placeholderBank: 'Ex: BNA, CPÂ, BEA...',

        // Date locale
        dateLocale: 'fr-FR',

        // ── Static HTML UI labels (data-i18n) ──
        mainCart: '🛒 Panier principal',
        quickClient: '⚡ Client rapide',
        emptyQuickCart: 'Aucun article rapide pour le moment',
        waitingScan: '📦 En attente d\'un scan...',
        discountPromo: '🏷️ Remise (Promo)',
        paymentStatus: 'Statut de paiement:',
        printer: '🖨️ Imprimante:',
        printerReady: '✅ Prêt',
        quickProducts: '🛍️ Produits rapides',
        clickToAdd: 'Cliquez pour ajouter au panier',
        btnAdd: '🔍 Ajouter',
        // History
        salesHistory: '🧾 Historique des ventes',
        sales: 'ventes',
        filter: 'Filtrer',
        reset: 'Réinitialiser',
        totalRevenue: 'Revenu total',
        totalProfit: 'Profit total',
        searchSalePlaceholder: 'Rechercher produit, client...',
        noSalesFound: 'Aucune vente trouvée',
        reprint: '🖨️ Réimprimer',
        refund: '↩️ Rembourser',
        refunded: 'Remboursé',
        refundConfirm: '⚠️ Confirmer le remboursement de cette vente ?',
        refundCompleted: 'Remboursement effectué avec succès',
        refundFailed: '❌ Échec du remboursement',

        btnPrint: '🖨️ Imprimer',
        manualBarcodePlaceholder: '🔍 Code-barres manuel',
        barcodeLabel: 'Code-barres *',
        barcodeScanPlaceholder: 'Scanner ou taper le code',
        referenceLabel: 'Code de référence',
        referencePlaceholder: 'ex: REF-001',
        nameLabel: 'Nom du produit *',
        namePlaceholder: 'ex: Mouchoir 50pcs',
        categoryLabel: 'Catégorie',
        selectCategoryPrompt: '-- Sélectionner une catégorie --',
        unitLabel: 'Unité *',
        pieceOption: 'Pièce',
        meterOption: 'Mètre',
        purchasePriceLabel: 'Prix d\'achat (DA) *',
        purchasePriceHint: 'Coût d\'achat du produit (pour calculer les bénéfices)',
        priceLabel: 'Prix (DA) *',
        stockLabelInput: 'Stock *',
        supplierLabel: 'Fournisseur',
        noSupplier: '-- Aucun fournisseur --',
        minStockLabel: 'Stock minimum',
        imageLabel: 'Image du produit',
        imageHint: 'JPG, PNG, GIF, WebP • Max 2 Mo',
        categoryManagement: '🏷️ Gestion des Catégories',
        newCategoryInputPlaceholder: 'Nom de la nouvelle catégorie',
        addCategory: '➕ Ajouter',
        loadingCategories: 'Chargement des catégories...',
        tableImage: 'Image',
        tableBarcode: 'Code-barres',
        tableNom: 'Nom',
        tableCategory: 'Catégorie',
        tableUnit: 'Unité',
        tableSalePrice: 'Prix vente (DA)',
        tablePurchasePrice: 'Prix achat (DA)',
        tableProfitUnit: 'Profit/unité',
        tableMargin: 'Marge',
        tableStock: 'Stock',
        tableActions: 'Actions',
        noProductsInCatalog: 'Aucun produit dans le catalogue',
        searchProductPlaceholder: 'Rechercher un produit (nom, code-barres, catégorie, référence)...',
        clearSearch: '✕ Effacer',
        supplierNameLabel: 'Nom du fournisseur *',
        supplierManagement: '🏷️ Gestion des Fournisseurs',
        supplierPhone: 'Téléphone',
        supplierAddress: 'Adresse',
        supplierEmail: 'Email (optionnel)',
        supplierNif: 'NIF / NIS (optionnel)',
        supplierNifPlaceholder: 'Numéro fiscal',
        supplierSearchPlaceholder: '🔍 Rechercher un fournisseur...',
        noSuppliers: 'Aucun fournisseur',
        receptionTitle: '📦 Bon de Réception',
        receptionSupplier: 'Fournisseur *',
        receptionSelectPrompt: '-- Sélectionner --',
        receptionDate: 'Date *',
        receptionInvoice: 'N° Facture / Référence',
        receptionInvoicePlaceholder: 'Facture fournisseur (optionnel)',
        receptionItems: 'Articles reçus',
        addReceptionItem: '➕ Ajouter un article',
        saveReception: '✅ Enregistrer la réception',
        purchaseHistory: '📋 Historique des Réceptions',
        allSuppliersFilter: 'Tous les fournisseurs',
        noReception: 'Aucune réception',
        lowStockAlerts: '⚠️ Alertes Stock Bas',
        loading: 'Chargement...',
        settingsDesignTitle: '🎨 Design du site',
        settingsDesignDesc: 'Choisissez un thème pour personnaliser l\'apparence',
        openingFloatLabel: 'Fond de caisse (DA)',
        openingFloatHint: 'Montant de la monnaie d\'ouverture journalière',
        arabicNumeralsLabel: '🌏 Chiffres arabes-indic',
        arabicNumeralsHint: 'Afficher les chiffres en notation arabe-indic (٠١٢٣٤٥٦٧٨٩) en mode AR',
        saveBtn: '💾 Sauvegarder',
        resetBtn: '↺ Réinitialiser',
        downloadBackup: '💾 Télécharger la sauvegarde',
        resetAllBtn: '⚠️ Tout réinitialiser',
        fullBackupBtn: '💾 Sauvegarde complète',
        restoreLabel: 'Restaurer une sauvegarde',
        dbInfoLabel: 'Base de données:',
        storageInfoLabel: 'Stockage:',
        loadingInfo: 'Chargement...',
        usersManagement: '🗣️ Gestion des utilisateurs',
        addUser: '➕ Ajouter un utilisateur',
        activityLog: '📋 Historique des activités',
        viewAllHistory: '📄 Voir tout l\'historique',
        activityHint: 'Consultez toutes les actions effectuées par les utilisateurs. Cliquez sur 📋 dans la liste d\'un utilisateur pour voir son historique individuel.',
        selfProfileTitle: '👤 Mon Profil',
        profileNameLabel: 'Nom',
        profileRoleLabel: 'Rôle',
        saveProfile: '💾 Enregistrer',
        changeMyPinBtn: '🔑 Changer mon PIN',
        editProductModal: '✏️ Modifier le produit',
        customerDetailTitle: '👤 Client',
        phoneLabel: 'Téléphone:',
        addressLabel: 'Adresse:',
        registrationDateLabel: 'Date d\'inscription:',
        totalDebtLabel: 'Dette totale:',
        debtHistoryTitle: '📋 Historique des dettes',
        payDebtsBtn: '💰 Payer les dettes sélectionnées',
        closeModal: 'Fermer',
        newUserTitle: '➕ Nouvel utilisateur',
        userFullName: 'Nom complet *',
        userPinLabel: 'PIN (4-6 chiffres) *',
        userRoleLabel: 'Rôle *',
        roleCaissier: 'Caissier',
        roleGerant: 'Gérant',
        roleAdmin: 'Administrateur',
        forcePinChangeLabel: '🔑 Forcer le changement de PIN à la prochaine connexion',
        permissionsLabel: '🔐 Permissions personnalisées',
        permissionsOptionalLabel: '(optionnel)',
        permissionsHintLabel: 'Laissez vide pour utiliser les permissions par défaut du rôle.',
        saveUserBtn: '💾 Enregistrer',
        cancelBtn: 'Annuler',
        pinChangeTitle: '🔑 Changer le PIN de ',
        newPinLabel: 'Nouveau PIN (4-6 chiffres) *',
        confirmPinLabel: 'Confirmer le PIN *',
        changePinBtn: '💾 Changer le PIN',
        adminPinConfirmTitle: '🔐 Confirmation Admin requise',
        adminPinSubtitle: 'Entrez le PIN d\'un administrateur',
        mandatoryPinTitle: '🔑 Changement de PIN obligatoire',
        mandatoryPinDesc: 'Votre PIN par défaut (0000) doit être changé pour des raisons de sécurité.',
        auditLogTitle: '📋 Journal d\'audit',
        auditFilterAllUsers: 'Tous les utilisateurs',
        auditFilterAllActions: 'Toutes les actions',
        auditFilterBtn: '🔍 Filtrer',
        auditDateHeader: 'Date',
        auditUserHeader: 'Utilisateur',
        auditActionHeader: 'Action',
        auditDetailsHeader: 'Détails',
        auditLoading: 'Chargement...',
        themeApplied: 'Thème appliqué',

        // cart.js additions
        waitingScan: '📦 En attente d\'un scan...',
        addedToCartQty: '✅ {{qty}}{{unit}} {{name}} ajouté {{location}}',
        toCart: 'au panier',
        toQuickCart: 'au panier rapide',
        enterMeterQty: 'Entrez la quantité en mètres',
        confirmQty: '✅ Ajouter',
        decimalHint: 'Utilisez le point (.) pour les décimales (ex: 2.5)',
        stockAvailable: 'Stock disponible: <strong>{{stock}} m</strong>',

        // customers.js additions
        noPhone: '📱 Pas de téléphone',
        debtLabel: '🔴 Dette',
        confirmDeleteCustomer: 'Supprimer ce client ?',
        confirmDeleteSaleTransaction: 'Supprimer cette transaction et restituer le stock',
        payDebtsConfirm: 'Payer {{count}} dette(s) pour un total de {{total}} {{currency}} ?',
        registrationFailed: '❌ Échec de l\'enregistrement: {{error}}',

        // suppliers.js additions
        supplierEditTitle: 'Modifier',
        supplierDeleteTitle: 'Supprimer',
        supplierEditBtn: '✏️ Modifier',
        supplierConfirmDelete: '⚠️ Supprimer le fournisseur "{{name}}" ?\n\nLes produits liés ne seront pas supprimés.',
        allSuppliers: 'Tous les fournisseurs',
        noSupplierOption: '-- Aucun fournisseur --',
        productPlaceholder: '🔍 Produit...',
        qtyPlaceholder: 'Qté',
        pricePlaceholder: 'Prix unit.',
        removeItemTitle: 'Retirer',
        noProductItem: 'Aucun produit',
        confirmSaveReception: '📦 Enregistrer la réception de {{count}} article(s) ?\n\nTotal: {{total}} DA\n\nLe stock sera automatiquement mis à jour.',
        receptionErrorToast: '❌ Erreur lors de l\'enregistrement',
        unknownSupplier: 'Fournisseur inconnu',
        facturePrefix: '• Facture: ',
        articlesCountSuffix: 'article(s)',
        loadingError: '❌ Erreur de chargement',
        aboveThreshold: 'Tous les stocks sont au-dessus du seuil',
        remainingCount: 'restant(s)',
        thresholdLabel: '/ seuil: ',
        errorTitle: 'Erreur',

        // inventory.js additions
        categoryCreated: '✅ Catégorie "{{name}}" créée',
        categoryDeleted: '✅ Catégorie "{{name}}" supprimée',
        categoryExistsWithProducts: '⚠️ La catégorie "{{name}}" existe déjà (utilisée par des produits)',
        categoryDeleteConfirm: '⚠️ Supprimer la catégorie "{{name}}" ?\n{{count}} produit(s) seront déplacés vers "{{uncategorized}}".',
        categoryDeletedMoved: '✅ Catégorie supprimée - {{count}} produits déplacés vers "{{uncategorized}}"',
        barcodeExists: '⚠️ Un produit avec ce code-barres existe déjà: {{name}}',
        autoBarcodeGenerated: '🔢 Code-barres généré: {{barcode}}',
        productAddedToStock: '✅ {{name}} ajouté au stock',
        productUpdatedMsg: '✅ {{name}} mis à jour',
        stockUpdatedMsg: '✅ Stock mis à jour ({{name}})',
        batchNumberLabel: 'N° de lot',
        expiryDateLabel: 'Date de péremption',
        confirmDeleteProduct: '⚠️ Supprimer le produit "{{barcode}}" ?',
        confirmDeleteAllProductsAgain: 'Êtes-vous absolument sûr ?',

        // payment.js additions
        amountReceived: 'Montant reçu :',
        checkNumber: 'N° Chèque :',
        checkPlaceholder: 'Ex: BNA, CPÂ, BEA...',
        ccpNumber: 'N° CCP :',
        referenceLabel: 'Référence :',
        baridiMobNumber: 'N° BaridiMob :',
        creditSaleLabel: '⚠️ Vente à crédit (dette)',
        creditSaleDesc: 'Le montant total sera enregistré comme dette du client.',
        creditSaleNeedsClient: 'Un client doit être sélectionné pour cette option.',
        paymentPaidLabel: '✅ Payé — {{method}}',
        paymentCreditLabel: '❌ Crédit (dette)',
        paymentPartialLabel: '⏳ Partiel — {{method}}',

        // transaction.js additions
        transactionCompleteMsg: '✅ Transaction complète ! Total: {{total}} {{currency}} | Profit: {{profit}} {{currency}}',
        debtRecordedMsg: '⚠️ Vente enregistrée - Dette: {{total}} {{currency}}',
        quickCustomerBtn: '⚡ Client rapide',

        // analytics-view.js additions
        refreshButton: '🔄 Rafraîchir',
        statusPaidLabel: '✓ Payée',
        remainingDebtLabel: '⚠️ Dette restante: {{amount}} {{currency}}',
        quantityPlaceholder: 'Qté',
        regularCustomerOption: '🔄 Client régulier (sans profil)',
        statusPaidOption: '✅ Payé',
        statusDebtOption: '⚠️ Dette',
        statusPartialOption: '⏳ Partiel',

        // analytics-charts.js additions
        allFilterOption: 'Tout',

        // analytics dashboard design
        currencyShort: 'DA',
        analyticsEyebrow: 'Statistiques & performances',
        analyticsChartsTitle: 'Analyse des ventes',
        analyticsChartsHint: 'Personnalisez la visualisation ci-dessous',
        chartType: 'Type de graphique',
        metricLabel: 'Métrique',
        dateRangeLabel: 'Période',
        fromLabel: 'Du',
        toLabel: 'Au',
        paletteLabel: 'Palette',
        gridLabel: 'Grille',
        labelsLabel: 'Étiquettes',
        legendLabel: 'Légende',
        animateLabel: 'Animation',
        fontSizeLabel: 'Taille police',
        lineWidthLabel: 'Épaisseur',
        pointRadiusLabel: 'Points',
        fillOpacityLabel: 'Opacité',
        borderRadiusLabel: 'Arrondi',
        revenueTrendLabel: 'Recette (14j)',
        profitTrendLabel: 'Bénéfice (14j)',
        itemsTrendLabel: 'Articles (14j)',
        chartTypeBar: 'Barres',
        chartTypeHorizontalBar: 'Barres horizontales',
        chartTypeLine: 'Lignes',
        chartTypeArea: 'Aire',
        chartTypePie: 'Camembert',
        chartTypeDoughnut: 'Donut',
        chartTypeRadar: 'Radar',
        chartTypeStackedBar: 'Barres empilées',
        chartTypeScatter: 'Nuage de points',
        metricRevenue: 'Recette',
        metricProfit: 'Bénéfice',
        metricItems: 'Articles vendus',
        metricSales: 'Nombre de ventes',
        metricMargin: 'Marge %',
        metricDebt: 'Dette en cours',
        metricCustomers: 'Par client',
        metricProducts: 'Par produit',
        metricCategories: 'Par catégorie',
        metricHourly: 'Par heure',
        metricDayOfWeek: 'Par jour de la semaine',
        metricPaymentStatus: 'Statut de paiement',
        metricRevenueVsProfit: 'Recette vs Bénéfice',
        metricItemsVsRevenue: 'Articles vs Recette',
        metricTopProducts: 'Top produits',
        metricTopCustomers: 'Top clients',
        chartDailyRevenue: 'Recette journalière ({{cur}})',
        chartDailyProfit: 'Bénéfice journalier ({{cur}})',
        chartDailyItems: 'Articles vendus par jour',
        chartDailySales: 'Nombre de ventes par jour',
        chartDailyMargin: 'Marge journalière %',
        chartOutstandingDebt: 'Dette en cours: {{amount}}',
        chartRevenueCustomer: 'Recette par client ({{cur}})',
        chartRevenueProduct: 'Recette par produit ({{cur}})',
        chartRevenueCategory: 'Recette par catégorie ({{cur}})',
        chartItemsHour: 'Articles vendus par heure',
        chartItemsDow: 'Articles vendus par jour de la semaine',
        chartPaymentStatus: 'Répartition des statuts de paiement',
        chartRevenueVsProfit: 'Recette vs Bénéfice ({{cur}})',
        chartItemsVsRevenue: 'Articles vs Recette ({{cur}})',
        chartTopProducts: 'Top produits par recette ({{cur}})',
        chartTopCustomers: 'Top clients par recette ({{cur}})',
        chartRevenue: 'Recette',

        // utils.js additions
        paidDisplay: '✅ Payé',
        notPaidDisplay: '❌ Non Payé',

        // audit.js additions
        systemUser: 'Système',
        noEntries: 'Aucune entrée',
        allActionsFilter: 'Toutes les actions',
        entriesCount: '{{count}} entrée(s)',
        entriesForUser: '{{count}} entrée(s) pour cet utilisateur',
        selectUserFilter: 'Tous les utilisateurs',

        // exports.js additions
        csvHeaderRow: 'ID Vente,Date,Client,Articles,Sous-total,TVA,Remise,Total,Payé,Reste,Statut',

        // promotions.js additions
        promoBuyPrefix: 'Achetez ',
        promoFreeSuffix: ' offert ',
        promoTypeLabel: 'Type: ',
        promoScopePrefix: ' | Portée: ',
        promoEditBtn: '✏️ Modifier',
        promoLabelAll: 'Tous',
        promoLabelCat: 'Cat: ',
        promoLabelProd: 'Prod: ',
        promoLabelSupplier: 'Fourn: ',
        promoLabelClient: 'Client: ',
        promoLabelPriceMin: 'Prix ≥ ',
        promoLabelPriceMax: 'Prix ≤ ',
        promoTieredSuffix: ' si qty ≥ ',
        promoCartPrefix: 'si total ≥ ',
        promoCartPercentSuffix: ' sur le total',
        promoCartFixedSuffix: ' sur le total',
        promoNeedSupplierHint: 'Veuillez créer des fournisseurs dans la section Fournisseurs',

        // store display
        fromStore: 'au magasin',
        totalItemsCount: '{{count}} produits • {{units}} unités',
        purchaseCostLabel: 'Coût d\'achat:',

        // Variants
        variants: 'Variantes',
        addVariant: '➕ Ajouter une variante',
        variantName: 'Nom de la variante',
        variantType: 'Type',
        variantTypeColor: 'Couleur',
        variantTypeSize: 'Taille',
        variantTypeOther: 'Autre',
        variantPrice: 'Prix (optionnel)',
        variantStock: 'Stock (optionnel)',
        variantBarcode: 'Code-barres (optionnel)',
        variantSave: '💾 Enregistrer la variante',
        variantDelete: '🗑️ Supprimer',
        variantDeleteConfirm: 'Supprimer la variante « {{name}} » ?',
        variantSaved: 'Variante enregistrée',
        variantDeleted: 'Variante supprimée',
        noVariants: 'Aucune variante pour ce produit',
        chooseVariant: 'Choisir une variante',
        variantFor: 'Variante pour {{name}}',
        variantPick: 'Sélectionnez une variante',
        scanVariantBarcode: 'Scanner le code-barres de la variante',
        manageVariants: '🎨 Gérer les variantes',
        variantAddedToCart: '{{name}} ({{variant}}) ajouté au panier',

        // Classic POS terminal (structure classic)
        classicCartTitle: 'Panier — Caisse',
        classicCatTitle: 'Produits rapides',
        classicReducedPrice: 'Réduit',
        classicQuickCart: '⚡ Client rapide',
        classicQuickTotal: 'Total rapide',
        classicThisSale: 'Montant de la vente',
        classicTendered: 'Tendue',
        classicLastSale: 'Dernière vente',
        classicChange: 'Monnaie',
        classicClear: 'EFF',
        classicQtyMult: '×Qté',
        classicPay: 'PAYER',
        classicVoid: 'ANN',
        classicPrint: 'IMPRIMER',
        classicTicket: 'TICKET',
        classicEdit: 'Éditer',
        classicDelete: 'Effacer',
        classicTab1: 'Fonctions',
        classicTab2: 'Remises',
        classicTab3: 'Paiement',
        classicSearch: 'Recherche',
        classicClient: 'Client',
        classicClearCart: 'Vider panier',
        classicExit: 'Quitter',
        classicRemoveItem: 'Retirer l’article',
        classicDiscountPct: 'Remise %',
        classicDiscountAmount: 'Remise montant',
        classicFreePrice: 'Prix libre',
        classicSetQty: 'Qté libre',
        classicCash: 'Espèces',
        classicCredit: 'Crédit',
        classicCheck: 'Chèque',
        classicPaymentMethods: 'Moyens de paiement',
        classicProducts: 'Produits',
        classicNoProducts: 'Aucun produit',
        classicAllCat: 'Tous',
        classicSearchPlaceholder: 'Rechercher un produit...',
        classicSearchNoResult: 'Aucun résultat',
        classicSelectRowFirst: 'Sélectionnez d’abord un article',
        classicRowIndicator: 'ligne',
        classicSaleDone: 'Vente enregistrée',
        classicChangeDue: 'Rendu monnaie',
        classicExact: 'ESP',
        classicLastSaleNone: '—',
        classicDecimalHint: 'Valeur décimale acceptée (ex : 2.5)',
        outOfStockShort: 'Épuisé',

        // payment.js / settings.js payment-methods additions
        bankName: 'Banque :',
        paymentFields: 'champ(s)',
        paymentRemove: 'Retirer',
        confirmRemovePaymentMethod: '⚠️ Retirer ce moyen de paiement de la caisse ?',
        confirmResetPaymentMethods: '⚠️ Restaurer tous les moyens de paiement par défaut ?',
        paymentMethodNameRequired: 'Veuillez saisir un nom pour le moyen de paiement'
    },

    // Settings tabs
    settingsGeneral: 'Général',
    settingsAppearance: 'Apparence',
    settingsCheckout: 'Caisse',
    settingsInventory: 'Stock',
    settingsReceipt: 'Ticket',
    settingsBackup: 'Sauvegarde',
    settingsSystem: 'Système',

    // Settings General
    shopName: 'Nom du magasin',
    shopAddress: 'Adresse',
    shopPhone: 'Téléphone',
    shopEmail: 'Email',
    locale: 'Locale',
    timezone: 'Fuseau horaire',
    dateFormat: 'Format de date',
    vatInclusive: 'Prix TTC',
    fiscalId: 'ID Fiscal / NIS',

    // Settings Appearance
    compactMode: 'Mode compact',
    showIcons: 'Afficher les icônes',
    animations: 'Animations',
    highContrast: 'Contraste élevé',
    fontSize: 'Taille police',
    density: 'Densité',

    // Settings Checkout
    autoFocusScanner: 'Focus auto scanner',
    autoAddQty: 'Ajout auto quantité',
    soundEnabled: 'Sons',
    vibrationEnabled: 'Vibration mobile',
    confirmClear: 'Confirmer vidage panier',
    askCustomer: 'Demander client',
    askCustomerPrompt: 'Aucun client sélectionné. Continuer cette vente sans client ?',
    askCustomerTitle: '👤 Choisir un client',
    askCustomerSubtitle: 'Cette vente sera enregistrée sans client si vous continuez.',
    continueWithoutCustomer: 'Continuer sans client',
    defaultPayment: 'Paiement défaut',
    rounding: 'Arrondi',
    quickCustomerEnabled: 'Client rapide activé',
    quickCustomerName: 'Nom client rapide',

    // Settings Inventory
    negativeStock: 'Stock négatif',
    trackBatches: 'Suivi lots/dates',
    autoBarcode: 'Code-barres auto',
    defaultUnit: 'Unité défaut',

    // Settings Receipt
    receiptHeader: 'En-tête ticket',
    receiptFooter: 'Pied de ticket',
    receiptLogo: 'Logo ticket',
    printAuto: 'Impression auto',
    copies: 'Copies',

    // Settings Backup
    autoBackup: 'Sauvegarde auto',
    backupInterval: 'Intervalle (min)',
    backupRetention: 'Rétention (jours)',
    cloudSync: 'Sync cloud',

    // Settings System
    version: 'Version',
    dbSize: 'Taille DB',
    storageUsed: 'Stockage utilisé',
    clearCache: 'Vider cache',
    resetAllData: 'Réinitialiser tout',

    // analytics-charts.js v2 (recreated dashboard)
    receivedLabel: 'Recette encaissée',
    salesValueLabel: 'Ventes (valeur)',
    debtCreatedLabel: 'Dettes créées',
    valueStockSaleLabel: 'Valeur stock (vente)',
    valueStockPurchaseLabel: 'Valeur stock (achat)',
    potentialProfitLabel: 'Bénéfice potentiel',
    totalStockLabel: 'Unités totales',
    dailyDetailTitle: '📊 Détail par jour',
    recentSalesTitle: '🕒 Dernières ventes',
    debtsByCustomerTitle: '💳 Dettes par client',
    categorySalesTitle: 'Ventes par catégorie',
    paymentBreakdownTitle: 'Statut de paiement',
    hourlySalesTitle: 'Ventes par heure',
    weekdaySalesTitle: 'Ventes par jour de la semaine',
    trendTitle: 'Recette & Profit',
    customerColumn: 'Client',
    dateColumn: 'Date',
    itemsColumn: 'Articles',
    remainingColumn: 'Reste',
    paidColumn: 'Payé',
    totalColumn: 'Total',
    statusColumn: 'Statut',
    debtColumn: 'Dette',
    uncategorized: 'Non catégorisé',
    noSalesYet: 'Aucune vente enregistrée',
    noDebts: 'Aucune dette en cours',
    dayMon: 'Lun',
    dayTue: 'Mar',
    dayWed: 'Mer',
    dayThu: 'Jeu',
    dayFri: 'Ven',
    daySat: 'Sam',
    daySun: 'Dim',

    // Bouton contextuel (clic droit)
    btnContextTitle: 'Personnaliser le bouton',
    btnContextHide: 'Masquer le bouton',
    btnContextShow: 'Afficher le bouton',
    btnContextColor: 'Couleur',
    btnContextShortcut: 'Raccourci clavier',
    btnContextShortcutSet: 'Appuyez sur une touche pour définir le raccourci (la même touche le retire)',
    btnContextShortcutEsc: 'Échap : annuler',
    btnContextShortcutCancel: 'Raccourci annulé',
    btnContextShortcutRemove: 'Effacer le raccourci',
    btnContextShortcutSaved: 'Raccourci enregistré',
    btnContextShortcutCleared: 'Raccourci retiré',
    btnContextColorDefault: 'Par défaut',
    btnContextColorGreen: 'Vert',
    btnContextColorRed: 'Rouge',
    btnContextColorOrange: 'Orange',
    btnContextColorBlue: 'Bleu',
    btnContextColorPurple: 'Violet',
    btnContextColorGray: 'Gris',
    btnContextColorBordeaux: 'Bordeaux',
    btnContextColorTurquoise: 'Turquoise',
    btnContextLarge: 'Bouton agrandi',
    btnContextReset: 'Réinitialiser le bouton',
    btnContextResetDone: 'Bouton réinitialisé',
    btnContextHiddenTitle: 'Boutons masqués',
    btnContextHiddenRestored: 'Bouton réaffiché',
    btnContextHiddenNone: 'Aucun bouton masqué',
    btnCustomNone: 'Aucun bouton personnalisé — cliquez droit sur un bouton pour le personnaliser',
    btnCustomHidden: 'Masqué',
    btnCustomRestore: '👁 Réafficher',
    btnCustomResetOne: '↺ Réinitialiser',
    btnCustomResetAllDone: 'Boutons réinitialisés',

};

